apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sportsrevyen
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
  readiness:
    path: isready
    initialDelay: 10
  replicas:
    min: 1
    max: 3
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: db-custom-4-16384
        databases:
          - name: sportsrevyen
            envVarPrefix: DATABASE
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sportsrevyen-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
